export const env = {
  DEMO_MODE: process.env.NEXT_PUBLIC_DEMO_MODE === 'true',
  CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME ?? '',
  CLOUDINARY_UPLOAD_PRESET: process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET ?? '',
} as const;
